### PR TITLE
Fix to allow non boolean

### LINKED ISSUE #11: Values are being cast to boolean
It seems the parameters passed are being cast to boolean, here's an example:

```yo my-generator --name="foo"```

```
    return this.optionOrPrompt(prompts).then(function (props) {
      console.log(props);
   }
```
Gives
```Map { name: true }```

### PR DESCRIPTION
**Pull request by eh-am**
Fixes #11

### CODE REVIEW

**Comment by davidhouweling** [comment]
@funwhilelost Just wondering, when will this be pushed to NPM as it still only have version 2.0.0.

**Comment by funwhilelost** [comment]
@sambaker could you push out 2.0.1 with these changes?

**Comment by clayrisser** [comment]
Great fix, could you please update this on npm.

**Comment by clayrisser** [comment]
Until it is updated on npm, you can use the following in your package.json

```json
{
  "dependancies": {
    "yeoman-option-or-prompt": "git+https://github.com/artefact-group/yeoman-option-or-prompt.git"
  }
}
```

**Pull request merged**
